# gem_api
#
# This file was automatically generated for Copyright (c) Gem
# 2019. All rights reserved. by APIMATIC v2.0 ( https://apimatic.io ).

require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'gem_api/api_helper.rb'
require_relative 'gem_api/gem_api_client.rb'

# Http
require_relative 'gem_api/http/http_call_back.rb'
require_relative 'gem_api/http/http_client.rb'
require_relative 'gem_api/http/http_method_enum.rb'
require_relative 'gem_api/http/http_request.rb'
require_relative 'gem_api/http/http_response.rb'
require_relative 'gem_api/http/http_context.rb'
require_relative 'gem_api/http/faraday_client.rb'
require_relative 'gem_api/http/auth/custom_header_auth.rb'

# Models
require_relative 'gem_api/models/base_model.rb'
require_relative 'gem_api/models/new_user.rb'
require_relative 'gem_api/models/user.rb'
require_relative 'gem_api/models/user_detail.rb'
require_relative 'gem_api/models/connection.rb'
require_relative 'gem_api/models/connection_detail.rb'
require_relative 'gem_api/models/transaction.rb'
require_relative 'gem_api/models/fee.rb'
require_relative 'gem_api/models/new_amount.rb'
require_relative 'gem_api/models/amount.rb'
require_relative 'gem_api/models/credentials_format.rb'
require_relative 'gem_api/models/message.rb'
require_relative 'gem_api/models/oauth_request_format.rb'
require_relative 'gem_api/models/institution.rb'
require_relative 'gem_api/models/new_institution_user.rb'
require_relative 'gem_api/models/institution_user.rb'
require_relative 'gem_api/models/institution_user_detail.rb'
require_relative 'gem_api/models/asset.rb'
require_relative 'gem_api/models/asset_detail.rb'
require_relative 'gem_api/models/asset_ticker.rb'
require_relative 'gem_api/models/new_transaction.rb'
require_relative 'gem_api/models/asset_price.rb'
require_relative 'gem_api/models/asset_price_series.rb'
require_relative 'gem_api/models/profile.rb'
require_relative 'gem_api/models/new_profile.rb'
require_relative 'gem_api/models/name.rb'
require_relative 'gem_api/models/phone_number.rb'
require_relative 'gem_api/models/profile_detail.rb'
require_relative 'gem_api/models/new_document.rb'
require_relative 'gem_api/models/document.rb'
require_relative 'gem_api/models/document_id.rb'
require_relative 'gem_api/models/passport.rb'
require_relative 'gem_api/models/drivers_license.rb'
require_relative 'gem_api/models/id_card.rb'
require_relative 'gem_api/models/document_file.rb'
require_relative 'gem_api/models/file.rb'
require_relative 'gem_api/models/file_data.rb'
require_relative 'gem_api/models/new_account.rb'
require_relative 'gem_api/models/account.rb'
require_relative 'gem_api/models/account_detail.rb'
require_relative 'gem_api/models/new_plaid_item.rb'
require_relative 'gem_api/models/plaid_item.rb'
require_relative 'gem_api/models/new_plaid_account.rb'
require_relative 'gem_api/models/plaid_account.rb'
require_relative 'gem_api/models/new_bank_account.rb'
require_relative 'gem_api/models/bank_account_holder.rb'
require_relative 'gem_api/models/address.rb'
require_relative 'gem_api/models/payment_method.rb'
require_relative 'gem_api/models/blockchain_address.rb'
require_relative 'gem_api/models/institution_account.rb'
require_relative 'gem_api/models/resource.rb'
require_relative 'gem_api/models/base_type.rb'
require_relative 'gem_api/models/base_type1.rb'
require_relative 'gem_api/models/field.rb'
require_relative 'gem_api/models/connection_status_enum.rb'
require_relative 'gem_api/models/transaction_status_enum.rb'
require_relative 'gem_api/models/transaction_type_enum.rb'
require_relative 'gem_api/models/institution_user_status_enum.rb'
require_relative 'gem_api/models/asset_categories_enum.rb'
require_relative 'gem_api/models/gender_enum.rb'
require_relative 'gem_api/models/profile_status_enum.rb'
require_relative 'gem_api/models/account_type_enum.rb'
require_relative 'gem_api/models/account_status_enum.rb'
require_relative 'gem_api/models/category_enum.rb'
require_relative 'gem_api/models/encoding_enum.rb'
require_relative 'gem_api/models/line_type_enum.rb'
require_relative 'gem_api/models/media_type_enum.rb'
require_relative 'gem_api/models/orientation_enum.rb'

# Exceptions
require_relative 'gem_api/exceptions/api_exception.rb'

require_relative 'gem_api/configuration.rb'

# Controllers
require_relative 'gem_api/controllers/base_controller.rb'
require_relative 'gem_api/controllers/connections_controller.rb'
require_relative 'gem_api/controllers/profiles_controller.rb'
require_relative 'gem_api/controllers/user_management_controller.rb'
require_relative 'gem_api/controllers/institutions_controller.rb'
require_relative 'gem_api/controllers/accounts_controller.rb'
require_relative 'gem_api/controllers/transactions_controller.rb'
require_relative 'gem_api/controllers/assets_controller.rb'
