# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.AccountType.description
  class AccountTypeEnum
    ACCOUNT_TYPE_ENUM = [
      # TODO: Write general description for PLAIDACCOUNT
      PLAIDACCOUNT = 'PlaidAccount'.freeze,

      # TODO: Write general description for BANKACCOUNT
      BANKACCOUNT = 'BankAccount'.freeze,

      # TODO: Write general description for CREDITCARD
      CREDITCARD = 'CreditCard'.freeze,

      # TODO: Write general description for DEBITCARD
      DEBITCARD = 'DebitCard'.freeze,

      # TODO: Write general description for EXCHANGEACCOUNT
      EXCHANGEACCOUNT = 'ExchangeAccount'.freeze,

      # TODO: Write general description for WALLET
      WALLET = 'Wallet'.freeze,

      # TODO: Write general description for BLOCKCHAINADDRESS
      BLOCKCHAINADDRESS = 'BlockchainAddress'.freeze
    ].freeze
  end
end
