# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.AccountStatus.description
  class AccountStatusEnum
    ACCOUNT_STATUS_ENUM = [
      # TODO: Write general description for PENDING
      PENDING = 'pending'.freeze,

      # TODO: Write general description for OPENED
      OPENED = 'opened'.freeze,

      # TODO: Write general description for PENDING_APPROVAL
      PENDING_APPROVAL = 'pending_approval'.freeze,

      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'available'.freeze,

      # TODO: Write general description for UNAVAILABLE
      UNAVAILABLE = 'unavailable'.freeze,

      # TODO: Write general description for CLOSED
      CLOSED = 'closed'.freeze
    ].freeze
  end
end
