# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.AssetCategories.description
  class AssetCategoriesEnum
    ASSET_CATEGORIES_ENUM = [
      # TODO: Write general description for CRYPTOCURRENCY
      CRYPTOCURRENCY = 'cryptocurrency'.freeze,

      # TODO: Write general description for FIAT
      FIAT = 'fiat'.freeze
    ].freeze
  end
end
