# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # Category.
  class CategoryEnum
    CATEGORY_ENUM = [
      # TODO: Write general description for GOVERNMENTID
      GOVERNMENTID = 'GovernmentID'.freeze,

      # TODO: Write general description for PROOFOFADDRESS
      PROOFOFADDRESS = 'ProofOfAddress'.freeze,

      # TODO: Write general description for BIOMETRIC
      BIOMETRIC = 'Biometric'.freeze
    ].freeze
  end
end
