# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.ConnectionStatus.description
  class ConnectionStatusEnum
    CONNECTION_STATUS_ENUM = [
      # TODO: Write general description for CONNECTED
      CONNECTED = 'connected'.freeze,

      # TODO: Write general description for FETCHING
      FETCHING = 'fetching'.freeze,

      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'available'.freeze,

      # TODO: Write general description for UNAVAILABLE
      UNAVAILABLE = 'unavailable'.freeze,

      # TODO: Write general description for REVOKED
      REVOKED = 'revoked'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for NEEDS_UPDATE
      NEEDS_UPDATE = 'needs_update'.freeze
    ].freeze
  end
end
