# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # Encoding.
  class EncodingEnum
    ENCODING_ENUM = [
      # TODO: Write general description for BASE64
      BASE64 = 'base64'.freeze
    ].freeze
  end
end
