# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.Gender.description
  class GenderEnum
    GENDER_ENUM = [
      # TODO: Write general description for MALE
      MALE = 'male'.freeze,

      # TODO: Write general description for FEMALE
      FEMALE = 'female'.freeze,

      # TODO: Write general description for OTHER
      OTHER = 'other'.freeze
    ].freeze
  end
end
