# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # InstitutionUserStatus.
  class InstitutionUserStatusEnum
    INSTITUTION_USER_STATUS_ENUM = [
      # TODO: Write general description for OPENED
      OPENED = 'opened'.freeze,

      # TODO: Write general description for PENDING_APPROVAL
      PENDING_APPROVAL = 'pending_approval'.freeze,

      # TODO: Write general description for REJECTED
      REJECTED = 'rejected'.freeze,

      # TODO: Write general description for AVAILABLE
      AVAILABLE = 'available'.freeze,

      # TODO: Write general description for CLOSED
      CLOSED = 'closed'.freeze,

      # TODO: Write general description for REVOKED
      REVOKED = 'revoked'.freeze
    ].freeze
  end
end
