# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # LineType.
  class LineTypeEnum
    LINE_TYPE_ENUM = [
      # TODO: Write general description for RESIDENTIAL
      RESIDENTIAL = 'residential'.freeze,

      # TODO: Write general description for COMMERCIAL
      COMMERCIAL = 'commercial'.freeze,

      # TODO: Write general description for MOBILE
      MOBILE = 'mobile'.freeze
    ].freeze
  end
end
