# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # MediaType.
  class MediaTypeEnum
    MEDIA_TYPE_ENUM = [
      # TODO: Write general description for ENUM_IMAGEPNG
      ENUM_IMAGEPNG = 'image/png'.freeze,

      # TODO: Write general description for ENUM_IMAGEJPEG
      ENUM_IMAGEJPEG = 'image/jpeg'.freeze,

      # TODO: Write general description for ENUM_APPLICATIONPDF
      ENUM_APPLICATIONPDF = 'application/pdf'.freeze,

      # TODO: Write general description for ENUM_APPLICATIONMSWORD
      ENUM_APPLICATIONMSWORD = 'application/msword'.freeze
    ].freeze
  end
end
