# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.ProfileStatus.description
  class ProfileStatusEnum
    PROFILE_STATUS_ENUM = [
      # TODO: Write general description for CREATED
      CREATED = 'created'.freeze,

      # TODO: Write general description for PENDING_VERIFICATION
      PENDING_VERIFICATION = 'pending_verification'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for VERIFIED
      VERIFIED = 'verified'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'expired'.freeze,

      # TODO: Write general description for REVOKED
      REVOKED = 'revoked'.freeze,

      # TODO: Write general description for UNAVAILABLE
      UNAVAILABLE = 'unavailable'.freeze,

      # TODO: Write general description for NEEDS_UPDATE
      NEEDS_UPDATE = 'needs_update'.freeze
    ].freeze
  end
end
