# gem_api
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

module GemApi
  # translation missing: en.swagger.models.TransactionStatus.description
  class TransactionStatusEnum
    TRANSACTION_STATUS_ENUM = [
      # TODO: Write general description for SUBMITTED
      SUBMITTED = 'submitted'.freeze,

      # TODO: Write general description for PROCESSING
      PROCESSING = 'processing'.freeze,

      # TODO: Write general description for COMPLETED
      COMPLETED = 'completed'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for REJECTED
      REJECTED = 'rejected'.freeze,

      # TODO: Write general description for CANCELED
      CANCELED = 'canceled'.freeze
    ].freeze
  end
end
